theme: jekyll-theme-primer
title: Saladin Archive
description: Archive and collection

# Build settings
source: docs
destination: _site
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  
# Exclude files from build
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
